import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<nav>
					<ul className="mt-2 flex justify-center space-x-4">
						<li>
							<ActiveLink
								href={"/"}
								className="text-gray-500 hover:text-gray-700"
								activeClassName="underline"
								exact
							>
								Home
							</ActiveLink>
						</li>
						<li>
							<ActiveLink
								href={"/products"}
								className="text-gray-500 hover:text-gray-700"
								activeClassName="underline"
								exact={false}
							>
								All
							</ActiveLink>
						</li>
					</ul>
				</nav>
				<section className="mx-auto max-w-md px-10 py-10 md:max-w-4xl lg:max-w-7xl">
					{children}
				</section>
				<footer>
					<p className="text-center text-gray-400">
						© {new Date().getFullYear()}{" "}
					</p>
				</footer>
			</body>
		</html>
	);
}
